pipeline {

	agent any
	
	stages {
		stage('Checkout')
		{
		    steps {			
				checkout([
                        $class                             : 'GitSCM'
                        , branches                         : [[name: "origin/master"]]
                        , doGenerateSubmoduleConfigurations: false
                        , extensions                       : [[$class: 'CleanBeforeCheckout']]
                        , submoduleCfg                     : []
                        , userRemoteConfigs                : [[url: 'https://github.com/iecat/BFF.git']]
                ])
		    }
		}
		
	}
	
}
