pipeline {

	agent any
	
	stages {
		stage('Checkout')
		{
		    steps {				
				checkout([
                        $class                             : 'GitSCM'
                        , branches                         : [[name: "origin/master"]]
                        , doGenerateSubmoduleConfigurations: false
                        , extensions                       : [[$class: 'CleanBeforeCheckout']]
                        , submoduleCfg                     : []
                        , userRemoteConfigs                : [[url: 'https://github.com/iecat/BFF.git']]
                ])
		    }
		}
				
		stage('Install packages') {
			steps {
				npm install
			}
		}
		stage ('Test')
		{
		    steps {
    			echo "test -----";
    			node -v;
    			npm prune;
    			npm install;
    			npm test;
		    }
		}
		
		stage ('Build')
		{
			steps {
				echo 'building the app';
				npm run build;
			}
		}
		
		stage ('Publish')
		{
			steps {
				echo 'this step should do the publish'
			}
		}
	}
	
}
